### ISSUE TITLE
[Bug]: I launched on windows

### ISSUE THREAD

**Issue by pugsforlifebruh12** [lovebrew/lovebrew#25]
### Software Version

0.5.3 (Latest)

### What Happened?

As soon as I booted it up on windows it closed after 1 second, I tried using Admin mode, But it won't work, 

### What was Expected?

I expected it to actually run

### Operating System

Windows

### Operating System Version

Windows 10

### Code of Conduct

- [x] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
It's a command line application, you don't run it like normal GUI apps. You'll need to use Command Prompt, PowerShell or Msys2 configured properly and run it from there.
